note/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.notes , name='notes'),
    # url(r'^(?P<id>\d+)$', views.detail),

    url(r'^(?P<slug>[-\w]+)/$', views.detail , name='note_detail'),

]

notes/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^note/' ,include('note.urls' , namespace='notes')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

note/models.py
from django.db import models
import datetime
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(blank=True, max_length=100)
    content = models.TextField(blank=True)
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)


    slug = models.SlugField(default='' , null = True , blank= True)
    active = models.BooleanField(default=True)
    tags = models.CharField(blank=True, max_length=100)

    img = models.ImageField(upload_to="notes_img")

    def save(self, *args , **kwargs):
        if not self.slug and self.title :
            self.slug = slugify(self.title)
        super(Note , self).save(*args , **kwargs)

    def split_tag(self):
        return self.tags.split(',')


    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Note'
        ordering = ['-created']

    def __str__(self):
        return self.title

note/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
# Create your views here.
from .models import Note



def notes(request):
    all_notes = Note.objects.all()
    context = {
     'all_notes' : all_notes ,
    }

    return render(request , 'all_notes.html' , context)


def detail(request , slug):
    note = get_object_or_404(Note , slug=slug)
    print(note)
    context = {
        'one_note' : note ,
    }
    return render(request , 'note_detail.html' , context)

note/templates/all_notes.html
{% extends "base.html" %}
{% block body %}


    {% for note in all_notes %}
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="{{note.img.url}}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{note.title}}</h5>
        <p class="card-text">{{note.content|truncatewords:10}}</p>
        <ul>
          {% for tags in note.split_tag %}
            <li>{{tags}}</li>
          {% endfor %}
          <p>{{note.created|date:'j M '}}</p>
        </ul>
        <a href="{% url 'notes:note_detail' slug=note.slug %}" class="card-link btn-know-more">Know More</a>
      </div>
    </div>
    {% endfor %}
{% endblock %}

note/templates/note_detail.html
{% extends "base.html" %}
{% block body %}


{{one_note.title}}

<p>{{one_note.content}}</p>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home-static/css/mystyle.css'%}">

    <title>Hello, world!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Notes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notes</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Login</a>
              <a class="dropdown-item" href="#">SignUp</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <h1>Welcome In Notes App</h1>


{% block body %}

{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>